#!/bin/bash

while getopts "v" OPT; do
    case "$OPT" in
	v)
	VERBOSE=1
	;;
    esac
done

if [ -e "/sys/hypervisor/type" ]; then
    if [ "$(cat /sys/hypervisor/type)" = xen ]; then
        DIR=/sys/hypervisor/version
        VERSION_EXTRA=$(cat $DIR/extra)
        if [ "$VERSION_EXTRA" = "-unstable" ]; then
            VERSION=unstable
        else
            VERSION="$(cat $DIR/major).$(cat $DIR/minor)$VERSION_EXTRA"
        fi
    else
        [ "$VERBOSE" ] && echo "WARING!  Can't read type from sysfs!" >&2
    fi
else
    [ "$VERBOSE" ] && echo "WARING!  Can't find hypervisor information in sysfs!" >&2
fi

echo "$VERSION"
exit 0
